services:
  frontend:
    container_name: frontend
    restart: always
    build: ./front-end
    ports:
      - "8080:8080"
    depends_on:
      - backend
    links:
      - backend
    environment:
      - VUE_APP_API_URL=http://backend:8001  
   
  
  backend:
    container_name: backend
    restart: always
    build: ./back-end
    ports:
      - "8001:8001"
    env_file:
      - ./back-end/.env