version: "3.9"

services:
  frontend:
    container_name: frontend
    restart: always
    build: ./front-end
    ports:
      - 8080:8080
    depends_on:
      - backend
   
  
  backend:
    container_name: backend
    restart: always
    build: ./back-end
    ports:
      - 8001:8001
    environment:
      - MONGO_URI=${MONGO_URI}
    